name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
    simple_deployment:
        runs-on: ubuntu-22.04 # Use Ubuntu 20.04 do not work anymore on GitHub Actions
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test