name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    simple_deployment:
      runs-on: ubuntu-22.04 # Use Ubuntu 20.04 do not work anymore on GitHub Actions
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Install dependencies
          run: npm ci
        - name: Check style
          run: npm run eslint
        - name: Build
          run: npm run build
        - name: Test
          run: npm run test
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests
          run: npm run test:e2e
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
        - name: Trigger Render Deployment
          if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
    tag_release:
      if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
      needs: simple_deployment
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.73.0
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              DEFAULT_BUMP: 'patch'

    notify:
      if: github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')
      needs: [simple_deployment, tag_release]
      runs-on: ubuntu-latest
      steps:
        - name: Notify Discord - Success
          if: needs.simple_deployment.result == 'success' && needs.tag_release.result == 'success'
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
            status: ${{ job.status }}
            title: "🚀 Deployment Successful"
            description: |
              A new version has been successfully deployed!
              
              **Version:** ${{ needs.tag_release.outputs.new_tag }}
              **Commit:** ${{ github.sha }}
              **Branch:** ${{ github.ref_name }}
              
              [View Changes](https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }})
            username: "GitHub Actions"
            color: 0x00ff00
            
        - name: Notify Discord - Failure
          if: needs.simple_deployment.result == 'failure' || needs.tag_release.result == 'failure'
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
            status: ${{ job.status }}
            title: "❌ Deployment Failed"
            description: |
              **Failed Step:** ${{ needs.simple_deployment.result == 'failure' && 'Build/Test' || 'Tag Release' }}
              **Commit:** ${{ github.sha }}
              **Branch:** ${{ github.ref_name }}
              
              [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
              [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
              
              **Error Details:**
              Please check the workflow run for more details.
            username: "GitHub Actions"
            color: 0xff0000